# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set environment variables to prevent Python from writing .pyc files and enable unbuffered logging
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Copy only the mcp directory because that's our project
COPY mcp/ ./mcp/

# Change working directory to the mcp folder
WORKDIR /app/mcp

# Upgrade pip
RUN pip install --upgrade pip

# Install build dependencies and then project package
RUN pip install .

# Expose port if necessary (the MCP uses stdio transport by default so not needed)

# Set entrypoint to run the MCP server. The API key can be passed as an environment variable or as an argument.
ENTRYPOINT ["agentmail-mcp"]

# Default command: if no api-key is provided, it will warn and run with limited functionality
CMD ["--api-key", "${AGENTMAIL_API_KEY}"]
